/**
 * PORT content model.
 *
 * `site.json` is generated by `npm run sync:content` and holds the raw pull of
 * portipoh.com (pages, paragraphs, images). This file is the editorial layer: it
 * curates that material into the stations you explore in the 3D space.
 *
 * To change wording, add an exhibit or reorder the space, edit `stations` below.
 * To refresh the underlying material, re-run `npm run sync:content`.
 */

import data from './site.json';

/* ------------------------------------------------------------------ raw types */

export type GalleryImage = {
  small: string;
  large: string;
  caption: string;
  width?: number;
  height?: number;
};

type RawImage = GalleryImage & { kind?: string; pageIds?: number[] };

type RawPage = {
  id: number;
  slug: string;
  title: string;
  parent: number;
  date: string;
  link: string;
  excerpt: string;
  paragraphs: string[];
  images: RawImage[];
  children: { id: number; slug: string; title: string }[];
};

type Raw = {
  generatedAt: string;
  source: string;
  counts: { pages: number; media: number; images: number };
  pages: RawPage[];
  images: RawImage[];
  terkini: {
    id: number;
    slug: string;
    title: string;
    date: string;
    paragraphs: string[];
    images: GalleryImage[];
  }[];
  portfolio: { id: number; slug: string; title: string; date: string; paragraphs: string[] }[];
};

const raw = data as unknown as Raw;

export const contentMeta = {
  generatedAt: raw.generatedAt,
  source: raw.source,
  counts: raw.counts,
};

/* ------------------------------------------------------------------ page helpers */

const pageById = new Map(raw.pages.map((p) => [p.id, p]));

export function page(id: number): RawPage | undefined {
  return pageById.get(id);
}

/** Elementor pages often lead with a title, breadcrumb and widget headings. */
const NOISE = new Set([
  'Home',
  'Selanjutnya',
  'Previous',
  'Next',
  'Bacaan Lanjut',
  'Daftar',
  'Pengenalan',
  'Objektif',
  'Konsep',
  'Impak',
  'Kesimpulan',
  'Video',
  'Ahli',
  'Lembaga',
  'Pengarah',
  'Pengurusan',
  'LOKASI KAMI',
]);

/** Real paragraphs from a page, with navigational debris removed. */
export function body(id: number, from = 0, count = 4): string[] {
  const p = pageById.get(id);
  if (!p) return [];
  const clean = p.paragraphs
    .map((s) => s.trim())
    .filter((s) => s.length > 24 && !NOISE.has(s) && s !== p.title);
  return clean.slice(from, from + count);
}

/** Every paragraph on a page, cleaned but uncapped. */
export function allBody(id: number): string[] {
  return body(id, 0, 200);
}

/** Images embedded on a given page. */
export function imagesOf(id: number, limit = 99): GalleryImage[] {
  const p = pageById.get(id);
  if (!p) return [];
  return p.images.slice(0, limit).map(({ small, large, caption, width, height }) => ({
    small,
    large,
    caption,
    width,
    height,
  }));
}

/** Standalone library assets (portraits, posters, partner logos, artwork shots). */
export function library(pattern: RegExp, limit = 8): GalleryImage[] {
  return raw.images
    .filter((i) => (i.kind === 'library' || !i.pageIds?.length) && pattern.test(i.caption))
    .slice(0, limit)
    .map(({ small, large, caption, width, height }) => ({ small, large, caption, width, height }));
}

/** Everything, de-duplicated — used for the welcome-stage backdrop. */
export const allImages: GalleryImage[] = raw.images.map(
  ({ small, large, caption, width, height }) => ({ small, large, caption, width, height }),
);

function dedupe(list: GalleryImage[]): GalleryImage[] {
  const seen = new Set<string>();
  return list.filter((img) => {
    if (seen.has(img.small)) return false;
    seen.add(img.small);
    return true;
  });
}

/* ------------------------------------------------------------------ station model */

export type GlyphKey =
  | 'compass'
  | 'stage'
  | 'brush'
  | 'frame'
  | 'wave'
  | 'beacon'
  | 'pin';

export type Exhibit = {
  id: string;
  title: string;
  meta: string;
  tagline: string;
  body: string[];
  bullets?: string[];
  images: GalleryImage[];
  /** Original page on portipoh.com, kept for "sumber asal" links. */
  source?: string;
};

export type StationSection = {
  heading: string;
  paragraphs: string[];
  bullets?: string[];
};

export type StationKind = 'corridor' | 'list' | 'about' | 'contact';

export type Station = {
  id: string;
  label: string;
  short: string;
  glyph: GlyphKey;
  accent: string;
  tagline: string;
  intro: string[];
  kind: StationKind;
  exhibits: Exhibit[];
  sections?: StationSection[];
  heroImage?: GalleryImage;
  partners?: GalleryImage[];
};

const ORG = 'https://portipoh.com';

/* ------------------------------------------------------------------ the space */

export const stations: Station[] = [
  /* ---------------------------------------------------------------- 1. TENTANG KAMI */
  {
    id: 'tentang',
    label: 'TENTANG KAMI',
    short: 'Tentang',
    glyph: 'compass',
    accent: '#4fd1ff',
    tagline: 'Siapa kami, dan mengapa kami ada.',
    kind: 'about',
    intro: [
      'PORT (People Of Remarkable Talents) merupakan jenama bagi Kampung Karyawan Amanjaya, sebuah agensi kebudayaan yang didanai sepenuhnya oleh Kerajaan Negeri Perak.',
      'Diasaskan pada tahun 2011, objektif utama PORT adalah untuk mengetengahkan bidang seni ke mata masyarakat melalui program yang melibatkan personaliti seni dan budaya dari dalam dan luar negara.',
    ],
    exhibits: [],
    heroImage: imagesOf(71)[0] ?? library(/header|img_/i, 1)[0],
    sections: [
      {
        heading: 'Objektif',
        paragraphs: body(71, 0, 2),
        bullets: [
          'Menyediakan peluang kepada belia Perak mengembangkan bakat dalam seni visual, seni persembahan, sastera dan filem.',
          'Menambah ilmu pengetahuan melalui program bicara seni dan forum.',
          'Menjadikan Ipoh sebagai hub budaya intelektual.',
        ],
      },
      {
        heading: 'Motto — “Unity Thru Arts”',
        paragraphs: [
          'Motto “Unity Thru Arts” menekankan kepentingan seni dan budaya sebagai satu platform penting untuk merayakan serta menjambatani bermacam jenis praktis dan pemikiran yang merentas bangsa dan latar belakang.',
        ],
      },
      {
        heading: 'Black House',
        paragraphs: body(427, 0, 2),
        bullets: [
          'Portdistro — jualan kraf dan merchandise',
          'Common Room — seni persembahan, pameran dan bengkel',
          'Dark Room — fotografi dan cetakan',
          'Studio Muzik',
          'Residensi Seni',
        ],
      },
      {
        heading: 'Lembaga Pengarah',
        paragraphs: [],
        bullets: [
          "YB Dato' Khairuddin b. Abu Hanipah — Pengarah",
          'Encik Mohamad Hamidi b. Baharuddin — Pengarah',
          'YB Puan Salina bt. Samsudin — Pengarah',
          'Prof. Madya Dr. Nur Hisham Ibrahim — Pengarah',
        ],
      },
    ],
  },

  /* ---------------------------------------------------------------- 2. PROGRAM UTAMA */
  {
    id: 'program',
    label: 'PROGRAM UTAMA',
    short: 'Program',
    glyph: 'stage',
    accent: '#ffb457',
    tagline: 'Tujuh program yang membentuk ekosistem seni Perak.',
    kind: 'corridor',
    intro: [
      'Dari arkib muzik hinggalah festival antarabangsa — inilah program teras PORT yang berjalan sepanjang tahun.',
    ],
    heroImage: imagesOf(12)[0],
    exhibits: [
      {
        id: 'amp',
        title: 'Arkib Muzik Perak',
        meta: 'Inisiatif Kearkiban · Berterusan',
        tagline: 'Mengumpul, mendokumentasi dan memelihara warisan muzik negeri Perak.',
        body: body(614, 0, 3),
        images: library(/_mg_|_dsc|img_/i, 5),
        source: `${ORG}/program-utama/arkib-muzik-perak/`,
      },
      {
        id: 'iiaf',
        title: 'Ipoh International Art Festival',
        meta: 'Festival Antarabangsa · 2019 — kini',
        tagline: 'Festival pelbagai disiplin yang mengundang penggiat seni dari dalam dan luar negara.',
        body: body(835, 0, 3),
        images: [
          ...imagesOf(799, 6),
          ...imagesOf(626, 4),
          ...imagesOf(835, 3),
        ].slice(0, 9),
        source: `${ORG}/program-utama/ipoh-international-art-festival/`,
      },
      {
        id: 'ims',
        title: 'Ipoh Music Symposium',
        meta: 'Simposium Muzik · 2019 — kini',
        tagline: 'Membuka perbincangan tentang kesan seni muzik ke atas masyarakat.',
        body: body(851, 0, 3),
        bullets: [
          '2019 — Muzik Independen',
          '2020 — Rock Kapak',
          '2021 — Nusantara',
          '2022 — Pop 60-an',
        ],
        images: [
          ...imagesOf(801, 6),
          ...imagesOf(803, 4),
          ...imagesOf(805, 3),
        ].slice(0, 9),
        source: `${ORG}/program-utama/ipoh-music-symposium/`,
      },
      {
        id: 'panggung',
        title: 'Projek Panggung',
        meta: 'Pentas Muzik · Dua kali sebulan',
        tagline: 'Inisiatif mengangkat penggiat seni muzik dari pelbagai genre dan peringkat umur.',
        body: body(811, 0, 3),
        images: imagesOf(811, 6),
        source: `${ORG}/program-utama/projek-panggung/`,
      },
      {
        id: 'dana',
        title: 'Dana Kreatif Perak',
        meta: 'Skim Pendanaan · @PORT',
        tagline:
          'Buat pertama kali dalam sejarah seni kreatif Malaysia, dana kreatif disalurkan atas nama Menteri Besar.',
        body: body(809, 0, 3),
        images: imagesOf(809, 9),
        source: `${ORG}/program-utama/dana-kreatif-perak/`,
      },
      {
        id: 'folio',
        title: 'PORT Folio & PORT Skool',
        meta: 'Bicara, Forum & Bengkel',
        tagline: 'Program modal insan untuk perkongsian ilmu seni, budaya dan warisan.',
        body: body(927, 0, 3),
        images: imagesOf(927, 9),
        source: `${ORG}/program-utama/port-folio-port-skool/`,
      },
      {
        id: 'portcast',
        title: 'PORTCAST',
        meta: 'Sembang Santai · Video',
        tagline: 'Sembang santai bersama tokoh, artis dan penggiat seni muzik Perak.',
        body: body(821, 0, 3),
        images: library(/poster|_mg_|_dsc/i, 6),
        source: `${ORG}/program-utama/port-cast/`,
      },
    ],
  },

  /* ---------------------------------------------------------------- 3. RESIDENSI SENI */
  {
    id: 'residensi',
    label: 'RESIDENSI SENI',
    short: 'Residensi',
    glyph: 'brush',
    accent: '#8b7bff',
    tagline: 'Ruang studio dan kamar rehat untuk pengkarya muda.',
    kind: 'corridor',
    intro: [
      'Residensi Seni diberikan dua kali setahun kepada penggiat seni visual dari Malaysia dan luar negara untuk menjalani residensi di Black House, PORT.',
      'Pada akhir tempoh tiga bulan, seniman mengadakan pameran karya “work-in-progress” atau studio terbuka bersama khalayak awam.',
    ],
    heroImage: library(/hafizuddin/i, 1)[0],
    exhibits: [
      {
        id: 'residensi-2021',
        title: 'Residensi 2021',
        meta: 'Sesi 1 · 17 Mac — 17 Jun 2021',
        tagline: 'Izzat Aziz dan Khalil Muhsain.',
        body: body(456, 0, 3),
        images: library(/_mg_|_dsc|hafizuddin/i, 5),
        source: `${ORG}/residensi-seni/residensi-2021/`,
      },
      {
        id: 'residensi-2022',
        title: 'Residensi 2022',
        meta: 'Sesi 2 · 23 Mei — 19 Ogos 2022',
        tagline: 'Fadhli Ariffin dan Hafizuddin Azman.',
        body: body(487, 0, 3),
        images: library(/hafizuddin|_dsc|_mg_/i, 6),
        source: `${ORG}/residensi-seni/residensi-2022/`,
      },
      {
        id: 'amir',
        title: 'Amir Zainorin',
        meta: 'Artis & Kurator · 10 Feb — 24 Mac 2022',
        tagline: 'Artis-kurator Malaysia yang menetap di Denmark sejak 2002.',
        body: body(583, 0, 3),
        images: library(/hafizuddin|_dsc/i, 4),
        source: `${ORG}/residensi-seni/artis-international/`,
      },
      {
        id: 'khalil',
        title: 'Khalil Muhsain — Tiang Tanah Air',
        meta: 'Residen 2021',
        tagline: 'Bahan tanah liat dan permukaan batuan di Gunung Lang, Ipoh.',
        body: body(555, 0, 3),
        images: library(/_mg_|_dsc/i, 4),
        source: `${ORG}/residensi-seni/residensi-2021/khalil-muhsain/`,
      },
      {
        id: 'izzat',
        title: 'Izzat Aziz — Membaik Runtuhnya',
        meta: 'Residen 2021',
        tagline: 'Plastik terbuang dari Pantai Pasir Bogak dijadikan naratif baharu.',
        body: body(509, 0, 3),
        images: library(/_dsc|_mg_/i, 4),
        source: `${ORG}/residensi-seni/residensi-2021/izat-aziz/`,
      },
      {
        id: 'fadhli',
        title: 'Fadhli Ariffin — Mandi Alam',
        meta: 'Residen 2022',
        tagline: 'Instalasi-performans tentang ritual mandi penawar di Kuala Kangsar.',
        body: body(568, 0, 3),
        images: library(/hafizuddin|_dsc/i, 4),
        source: `${ORG}/residensi-seni/residensi-2022/fadhli-ariffin/`,
      },
      {
        id: 'hafizuddin',
        title: 'Hafizuddin Azman — Memoranda Jiwa',
        meta: 'Residen 2022',
        tagline: 'Dua belas catan cat minyak diselang-seli perca audio orang awam.',
        body: body(574, 0, 3),
        images: library(/hafizuddin/i, 6),
        source: `${ORG}/residensi-seni/residensi-2022/hafizuddin-azman/`,
      },
    ],
  },

  /* ---------------------------------------------------------------- 4. PAMERAN */
  {
    id: 'pameran',
    label: 'PAMERAN & BUKU DIGITAL',
    short: 'Pameran',
    glyph: 'frame',
    accent: '#ff7ad9',
    tagline: 'Pameran yang telah berlangsung, dibukukan secara digital.',
    kind: 'corridor',
    intro: [
      'Setiap pameran PORT didokumentasikan dalam bentuk buku digital supaya boleh dibaca semula bila-bila masa.',
    ],
    heroImage: library(/kembali/i, 1)[0],
    exhibits: [
      {
        id: 'kembali-pulang',
        title: 'Kembali Pulang ke Sarang',
        meta: 'Tin Alley · 26 Ogos — 1 Oktober 2023',
        tagline: 'Aw Boon Xin dan Abdul Shakir (Grashopper) — kegawatan untuk kembali ke akar.',
        body: body(206, 0, 2),
        images: library(/kembali/i, 4),
      },
      {
        id: 'bentukan',
        title: 'Bentuk.An',
        meta: 'Pameran Residen',
        tagline: 'Fadhli Ariffin dan Hafizuddin Azman — idea baharu daripada adat dan sosiobudaya Perak.',
        body: body(206, 2, 1),
        images: library(/hafizuddin|direktori/i, 4),
      },
      {
        id: 'semesta',
        title: 'Semesta',
        meta: 'Pameran Kumpulan',
        tagline: 'Ruang dan waktu yang merangkumi segenap lapisan makna kehidupan.',
        body: body(206, 3, 1),
        images: library(/_mg_|_dsc|img_/i, 5),
      },
      {
        id: 'direktori',
        title: 'Direktori Kreatif Negeri Perak',
        meta: 'Pangkalan Data · Berterusan',
        tagline: 'Pendaftaran wajib bagi semua pencalonan dan program seni negeri.',
        body: [
          'Pendaftaran dalam Pengkalan Data Seni Kreatif Perak adalah wajib bagi semua pencalonan program anjuran PORT bagi pihak Kerajaan Negeri Perak.',
        ],
        images: library(/direktori|dbp/i, 4),
      },
    ],
  },

  /* ---------------------------------------------------------------- 5. ARKIB & MEDIA */
  {
    id: 'arkib',
    label: 'ARKIB & MEDIA',
    short: 'Arkib',
    glyph: 'wave',
    accent: '#5df2c0',
    tagline: 'Bahan rujukan, liputan media dan buku digital.',
    kind: 'list',
    intro: [
      'PORT menjalankan kerja-kerja kearkiban seni dan budaya negeri Perak — sebagai rujukan penyelidik, pembuat dasar, pelajar dan pemerhati budaya.',
    ],
    heroImage: library(/img_|header/i, 1)[0],
    exhibits: [
      {
        id: 'amp-arkib',
        title: 'Arkib Muzik Perak (AMP)',
        meta: 'Arkib · Muzik',
        tagline: 'Sumber rujukan kepelbagaian genre muzik negeri Perak.',
        body: body(614, 0, 3),
        images: library(/poster|_mg_/i, 4),
        source: `${ORG}/program-utama/arkib-muzik-perak/`,
      },
      {
        id: 'media-liputan',
        title: 'Liputan Media',
        meta: 'Media · Luar',
        tagline: 'Penulisan dan liputan mengenai PORT dan seniman Perak.',
        body: [
          'Karya dan program PORT telah diliput oleh media tempatan dan antarabangsa, termasuk tulisan mengenai penyertaan seniman Malaysia di pentas global.',
        ],
        images: library(/img_|header|direktori/i, 4),
        source: `${ORG}/media/`,
      },
      {
        id: 'buku-digital',
        title: 'Buku Digital',
        meta: 'Penerbitan · Dalam Talian',
        tagline: 'Dokumentasi pameran dalam bentuk bacaan digital.',
        body: [
          'Buku digital PORT menyimpan rekod pameran, karya dan nota kuratorial supaya ekosistem seni negeri ini dapat diakses oleh generasi akan datang.',
        ],
        images: library(/poster|direktori|kembali/i, 5),
        source: `${ORG}/buku-digital/`,
      },
      {
        id: 'portcast-arkib',
        title: 'PORTCAST',
        meta: 'Video · Temu Bual',
        tagline: 'Pendokumentasian video berdasarkan bahan simpanan Arkib Muzik Perak.',
        body: body(821, 0, 2),
        images: library(/poster_ims|_mg_/i, 4),
        source: `${ORG}/program-utama/port-cast/`,
      },
    ],
  },

  /* ---------------------------------------------------------------- 6. PROGRAM TERKINI */
  {
    id: 'terkini',
    label: 'PROGRAM TERKINI',
    short: 'Terkini',
    glyph: 'beacon',
    accent: '#ff6b6b',
    tagline: 'Apa yang sedang berjalan sekarang.',
    kind: 'list',
    intro: ['Pencalonan, jadual acara dan pengumuman terkini daripada PORT.'],
    heroImage: library(/hsdr9/i, 1)[0] ?? library(/poster_ims/i, 1)[0],
    exhibits: [
      {
        id: 'hsdr9',
        title: 'Hadiah Sastera Darul Ridzuan ke-9',
        meta: 'Pencalonan dibuka sehingga 13 April 2026',
        tagline:
          'Anugerah dwitahunan Kerajaan Negeri Perak untuk mengiktiraf sasterawan Perak.',
        body: [
          'Hadiah Sastera Darul Ridzuan (HSDR) kembali untuk kali ke-9 — dianjurkan secara dwitahunan oleh Kerajaan Negeri Perak untuk mengiktiraf para sasterawan yang berasal atau bermastautin di Perak.',
          'Genre yang dinilai merangkumi puisi, cerpen, novel, drama dan esei. Penganugerahan ini menjadi wadah penting dalam memartabatkan tradisi persuratan dan memupuk bakat baharu.',
          'Pendaftaran dalam Pengkalan Data Seni Kreatif Perak adalah wajib bagi semua pencalonan. Imbas kod QR pada poster rasmi untuk mendaftar.',
          'Dianjurkan oleh PORT bagi pihak Kerajaan Negeri Perak dengan kerjasama Dewan Bahasa dan Pustaka.',
        ],
        images: library(/hsdr9|dbp/i, 6),
      },
      {
        id: 'ims-2023',
        title: 'Ipoh Music Symposium 2023',
        meta: 'Jadual Acara',
        tagline: 'Simposium muzik tahunan bersama panelis jemputan.',
        body: [
          'IMS mengumpulkan input dan pelbagai perspektif mengenai bidang muzik melalui pembentangan makalah oleh panelis jemputan — membuka perbincangan tentang kesan seni muzik ke atas masyarakat.',
        ],
        images: library(/ims|jadual/i, 6),
      },
      {
        id: 'praktikal',
        title: 'Latihan Industri / Praktikal',
        meta: 'Peluang · Terbuka',
        tagline: 'Untuk pelajar praktikal atau latihan industri.',
        body: [
          'Hantarkan resume dan portfolio anda ke portipoh9@gmail.com atau hubungi 05-241 2287 (Puan Dayana).',
        ],
        bullets: [
          'Pereka Grafik',
          'Multimedia',
          'Penyiaran & Dokumentasi (Video & Filem)',
          'Sumber Manusia',
        ],
        images: library(/header|img_/i, 4),
      },
    ],
  },

  /* ---------------------------------------------------------------- 7. HUBUNGI & KUNJUNGI */
  {
    id: 'hubungi',
    label: 'HUBUNGI & KUNJUNGI',
    short: 'Hubungi',
    glyph: 'pin',
    accent: '#ffe066',
    tagline: 'Datang ke Black House, atau hubungi kami terus.',
    kind: 'contact',
    intro: [
      'PORT IPOH, No 09, Jalan Sultan Azlan Shah, 31400 Ipoh, Perak.',
      'Kami terbuka untuk kunjungan, kolaborasi, penyertaan program dan permohonan dana.',
    ],
    exhibits: [],
    heroImage: imagesOf(16)[0] ?? library(/header/i, 1)[0],
  },
];

export function stationById(id: string): Station | undefined {
  return stations.find((s) => s.id === id);
}

/** Contact details, kept in one place so the HUD and the station agree. */
export const contact = {
  name: 'PORT IPOH',
  addressLines: ['No 09, Jalan Sultan Azlan Shah', '31400 Ipoh, Perak'],
  phone: '+605-241 2287',
  phoneHref: 'tel:+6052412287',
  fax: '+605-241 2394',
  email: 'portipoh9@gmail.com',
  whatsapp: '6052412287',
  source: `${ORG}/hubungi-kami/`,
};

export const partners: GalleryImage[] = dedupe([
  ...library(/visitperak/i, 1),
  ...library(/tourismperak|tourism-perak/i, 1),
  ...library(/^tourism/i, 1),
  ...library(/dbp|kreatif/i, 1),
]);

/**
 * Where "Kunjungi" sends people. Paste a Google Maps embed URL here to show the real
 * map inside the space (Google Maps -> Share -> Embed a map -> copy the src="..." URL).
 * Leave it undefined to keep the purely fictional-space presentation.
 */
export const googleMapEmbedUrl: string | undefined = undefined;

/* ------------------------------------------------------------------ entrance frontage */

/**
 * Any image dropped into `src/assets/` named `entrance.*` is picked up automatically and
 * used as the PORT frontage in the approach and behind the entry screen. No code change
 * needed — just add the file and restart the dev server (or rebuild).
 */
const dropped = import.meta.glob('../assets/entrance.*', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>;

/** Program banner shipped by the live site — the fallback frontage. */
export const defaultEntranceImage: GalleryImage | undefined =
  library(/main_programme_header/i, 1)[0] ?? library(/header/i, 1)[0] ?? allImages[1];

/**
 * The photograph of PORT's front used in the approach sequence.
 *
 * Resolution order:
 *   1. `VITE_PORT_ENTRANCE=/some/url.jpg` in a `.env` file
 *   2. a file dropped at `src/assets/entrance.*`
 *   3. the banner synced from portipoh.com
 */
export const entranceImage: { large: string; small: string; caption: string } | undefined = (() => {
  const fromEnv = (import.meta.env.VITE_PORT_ENTRANCE as string | undefined)?.trim();
  if (fromEnv) return { large: fromEnv, small: fromEnv, caption: 'PORT' };
  const fromDisk = Object.values(dropped)[0];
  if (fromDisk) return { large: fromDisk, small: fromDisk, caption: 'PORT' };
  if (defaultEntranceImage) {
    return {
      large: defaultEntranceImage.large,
      small: defaultEntranceImage.small,
      caption: defaultEntranceImage.caption,
    };
  }
  return undefined;
})();

/** True when the frontage is a real dropped-in photo rather than the synced banner. */
export const entranceIsCustom = Boolean(
  (import.meta.env.VITE_PORT_ENTRANCE as string | undefined)?.trim() ||
    Object.values(dropped)[0],
);
